Add 'types' field to package.json
This way the distributed package correctly points at its typescript entrypoint. I would rather this pointed at a generated `.d.ts` file, personally, as pointing at normal `.ts` files has historically caused issues... but the build output doesn't currently specify `declarations: true`, so that'd need to be done first.

Prior to this change, the module resolves a little like so:
```
======== Resolving module 'vega-lite' from 'C:/Users/wwigh/Github/glacier/glacier/src/index.ts'. ========
Module resolution kind is not specified, using 'NodeJs'.
Loading module 'vega-lite' from 'node_modules' folder.
File 'C:/Users/wwigh/Github/glacier/glacier/src/node_modules/vega-lite.ts' does not exist.
File 'C:/Users/wwigh/Github/glacier/glacier/src/node_modules/vega-lite.tsx' does not exist.
File 'C:/Users/wwigh/Github/glacier/glacier/src/node_modules/vega-lite.d.ts' does not exist.
Found 'package.json' at 'C:/Users/wwigh/Github/glacier/glacier/src/node_modules/vega-lite/package.json'.
'package.json' does not have 'types' field.
File 'C:/Users/wwigh/Github/glacier/glacier/src/node_modules/vega-lite/index.ts' does not exist.
File 'C:/Users/wwigh/Github/glacier/glacier/src/node_modules/vega-lite/index.tsx' does not exist.
File 'C:/Users/wwigh/Github/glacier/glacier/src/node_modules/vega-lite/index.d.ts' does not exist.
File 'C:/Users/wwigh/Github/glacier/glacier/src/node_modules/@types/vega-lite.ts' does not exist.
File 'C:/Users/wwigh/Github/glacier/glacier/src/node_modules/@types/vega-lite.tsx' does not exist.
File 'C:/Users/wwigh/Github/glacier/glacier/src/node_modules/@types/vega-lite.d.ts' does not exist.
File 'C:/Users/wwigh/Github/glacier/glacier/src/node_modules/@types/vega-lite/package.json' does not exist.
File 'C:/Users/wwigh/Github/glacier/glacier/src/node_modules/@types/vega-lite/index.ts' does not exist.
File 'C:/Users/wwigh/Github/glacier/glacier/src/node_modules/@types/vega-lite/index.tsx' does not exist.
File 'C:/Users/wwigh/Github/glacier/glacier/src/node_modules/@types/vega-lite/index.d.ts' does not exist.
```
======== Module name 'vega-lite' was not resolved. ========
index.ts(2,21): error TS2307: Cannot find module 'vega-lite'.